---

- name: Install openssh
  apt:
    name: openssh-server

- name: Start and enable openssh
  service:
    name: ssh
    state: started
    enabled: yes

- name: Config openssh
  template:
      dest: /etc/ssh/sshd_config
      src: sshd_config.j2
      owner: root
      group: root
      mode: 0600
      validate: '/usr/sbin/sshd -T -f %s'
  notify: reload openssh
