---

- name: restart ntp
  service:
    name: ntp
    state: restarted

- name: reload openssh
  service:
    name: ssh
    state: reloaded

- name: restart openssh
  service:
    name: ssh
    state: restarted

- name: restart resolvconf
  service:
    name:
      resolvconf
    state: restarted

- name: newaliases
  command: newaliases

- name: apt-get update
  apt:
    update_cache: yes

- name: fail2ban reload
  service:
    name: fail2ban
    state: restarted
